CREATE DATABASE IF NOT EXISTS antojitos_bd;
USE antojitos_bd;

-- Desactivar comprobación de claves foráneas para evitar errores de dependencia
SET FOREIGN_KEY_CHECKS = 0;

-- Eliminar tablas en orden inverso a sus dependencias
DROP TABLE IF EXISTS DIRECCION;
DROP TABLE IF EXISTS REPARTOPEDIDO;
DROP TABLE IF EXISTS DETALLEPEDIDO;
DROP TABLE IF EXISTS DATOSPRODUCTO;
DROP TABLE IF EXISTS CREDITO;
DROP TABLE IF EXISTS FACTURA;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS TIPOEVENTO;
DROP TABLE IF EXISTS REPARTIDOR;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS SUCURSAL;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS CATEGORIAPRODUCTO;
DROP TABLE IF EXISTS DISTRITO;
DROP TABLE IF EXISTS MUNICIPIO;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS ACCESOUSUARIO;
DROP TABLE IF EXISTS OPCIONCRUD;
DROP TABLE IF EXISTS USUARIO;

-- Reactivar comprobación de claves foráneas
SET FOREIGN_KEY_CHECKS = 1;


-- Tablas de seguridad
CREATE TABLE USUARIO (
    ID_USUARIO VARCHAR(255) PRIMARY KEY,
    NOM_USUARIO  VARCHAR(255) NOT NULL,
    CLAVE        VARCHAR(255) NOT NULL
);

CREATE TABLE OPCIONCRUD (
    ID_OPCION   VARCHAR(255) PRIMARY KEY,
    DES_OPCION  VARCHAR(255) NOT NULL,
    NUM_CRUD    INT NOT NULL  -- 1=Crear, 2=Consultar, 3=Editar, 4=Eliminar
);

CREATE TABLE ACCESOUSUARIO (
    ID_OPCION   VARCHAR(255) NOT NULL,
    ID_USUARIO  VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_OPCION, ID_USUARIO),
    FOREIGN KEY (ID_OPCION) REFERENCES OPCIONCRUD(ID_OPCION),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- Tablas de negocio
-- 1 Tabla CLIENTE
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO       INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_DEPARTAMENTO   VARCHAR(255) NOT NULL,
    ACTIVO_DEPARTAMENTO   INT DEFAULT 1
);

-- 2 Tabla MUNICIPIO
CREATE TABLE MUNICIPIO (
    ID_DEPARTAMENTO    INT NOT NULL,
    ID_MUNICIPIO       INT NOT NULL,
    NOMBRE_MUNICIPIO   VARCHAR(255) NOT NULL,
    ACTIVO_MUNICIPIO   INT DEFAULT 1,
    PRIMARY KEY (ID_DEPARTAMENTO, ID_MUNICIPIO),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);

-- 3 Tabla DISTRITO
CREATE TABLE DISTRITO (
    ID_DEPARTAMENTO   INT NOT NULL,
    ID_MUNICIPIO      INT NOT NULL,
    ID_DISTRITO       INT NOT NULL,
    NOMBRE_DISTRITO   VARCHAR(255) NOT NULL,
    CODIGO_POSTAL     VARCHAR(255) NOT NULL,
    ACTIVO_DISTRITO   INT DEFAULT 1,
    PRIMARY KEY (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO),
    FOREIGN KEY (ID_DEPARTAMENTO, ID_MUNICIPIO)
        REFERENCES MUNICIPIO(ID_DEPARTAMENTO, ID_MUNICIPIO)
);

-- 4 Tabla Categoria Producto
CREATE TABLE CATEGORIAPRODUCTO (
    ID_CATEGORIAPRODUCTO     INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CATEGORIA         VARCHAR(255) NOT NULL,
    DESCRIPCION_CATEGORIA    VARCHAR(255) NOT NULL,
    DISPONIBLE_CATEGORIA     INT NOT NULL,
    HORA_DISPONIBLE_DESDE    VARCHAR(255) NOT NULL,
    HORA_DISPONIBLE_HASTA    VARCHAR(255) NOT NULL,
    ACTIVO_CATEGORIAPRODUCTO INT DEFAULT 1
);

-- 5 Tabla Producto
CREATE TABLE PRODUCTO (
    ID_PRODUCTO              INT AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORIAPRODUCTO     INT NOT NULL,
    NOMBRE_PRODUCTO          VARCHAR(255) NOT NULL,
    DESCRIPCION_PRODUCTO     VARCHAR(255),
    ACTIVO_PRODUCTO          INT DEFAULT 1,
    FOREIGN KEY (ID_CATEGORIAPRODUCTO)
        REFERENCES CATEGORIAPRODUCTO(ID_CATEGORIAPRODUCTO)
);

-- 6 Tabla Sucursal
CREATE TABLE SUCURSAL (
    ID_SUCURSAL                 INT AUTO_INCREMENT PRIMARY KEY,
    ID_DEPARTAMENTO             INT NOT NULL,
    ID_MUNICIPIO                INT NOT NULL,
    ID_DISTRITO                 INT NOT NULL,
    NOMBRE_SUCURSAL             VARCHAR(255) NOT NULL,
    DIRECCION_SUCURSAL          VARCHAR(255) NOT NULL,
    TELEFONO_SUCURSAL           VARCHAR(255) NOT NULL,
    HORARIO_APERTURA_SUCURSAL   VARCHAR(255) NOT NULL,
    HORARIO_CIERRE_SUCURSAL     VARCHAR(255) NOT NULL,
    ACTIVO_SUCURSAL             INT DEFAULT 1,
    FOREIGN KEY (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
        REFERENCES DISTRITO(ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
);

-- 7 Tabla Cliente
CREATE TABLE CLIENTE (
    ID_CLIENTE         INT AUTO_INCREMENT PRIMARY KEY,
    TELEFONO_CLIENTE   VARCHAR(255) NOT NULL,
    NOMBRE_CLIENTE     VARCHAR(255) NOT NULL,
    APELLIDO_CLIENTE   VARCHAR(255) NOT NULL,
    ACTIVO_CLIENTE     INT DEFAULT 1
);

-- 8 Tabla Repartidor
CREATE TABLE REPARTIDOR (
    ID_REPARTIDOR             INT AUTO_INCREMENT PRIMARY KEY,
    ID_DEPARTAMENTO           INT,
    ID_MUNICIPIO              INT,
    ID_DISTRITO               INT,
    TIPO_VEHICULO             VARCHAR(255),
    DISPONIBLE                INT NOT NULL,
    TELEFONO_REPARTIDOR       VARCHAR(255) NOT NULL,
    NOMBRE_REPARTIDOR         VARCHAR(255) NOT NULL,
    APELLIDO_REPARTIDOR       VARCHAR(255) NOT NULL,
    ACTIVO_REPARTIDOR         INT DEFAULT 1,
    FOREIGN KEY (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
        REFERENCES DISTRITO(ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
);

-- 9 Tabla Tipo Evento
CREATE TABLE TIPOEVENTO (
    ID_TIPO_EVENTO              INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TIPO_EVENTO          VARCHAR(255) NOT NULL,
    DESCRIPCION_TIPO_EVENTO     VARCHAR(255),
    MONTO_MINIMO                FLOAT NOT NULL,
    MONTO_MAXIMO                FLOAT NOT NULL,
    ACTIVO_TIPOEVENTO           INT NOT NULL DEFAULT 1
);

-- 10 Tabla pedido
CREATE TABLE PEDIDO (
    ID_PEDIDO           INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE          INT,
    ID_TIPO_EVENTO      INT,
    ID_SUCURSAL         INT NOT NULL,
    ID_REPARTIDOR       INT NOT NULL,
    FECHA_HORA_PEDIDO   VARCHAR(255) NOT NULL,
    ESTADO_PEDIDO       VARCHAR(255) NOT NULL,
    ACTIVO_PEDIDO       INT NOT NULL DEFAULT 1,
    FOREIGN KEY (ID_CLIENTE)        REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_TIPO_EVENTO)    REFERENCES TIPOEVENTO(ID_TIPO_EVENTO),
    FOREIGN KEY (ID_REPARTIDOR)     REFERENCES REPARTIDOR(ID_REPARTIDOR),
    FOREIGN KEY (ID_SUCURSAL)       REFERENCES SUCURSAL(ID_SUCURSAL)
);

-- 11 Tabla Factura
CREATE TABLE FACTURA (
    ID_FACTURA       INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO        INT NOT NULL UNIQUE,
    FECHA_EMISION    VARCHAR(255) NOT NULL,
    MONTO_TOTAL      FLOAT NOT NULL CHECK (MONTO_TOTAL > 0),
    TIPO_PAGO        VARCHAR(255) NOT NULL,
    ESTADO_FACTURA   VARCHAR(255) NOT NULL,
    ES_CREDITO       INT NOT NULL CHECK (ES_CREDITO IN (0,1)),
    FOREIGN KEY (ID_PEDIDO)
        REFERENCES PEDIDO(ID_PEDIDO)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- 12 tABLA CREDITO
CREATE TABLE CREDITO (
    ID_CREDITO               INT AUTO_INCREMENT PRIMARY KEY,
    ID_FACTURA               INT NOT NULL UNIQUE,
    MONTO_AUTORIZADO_CREDITO FLOAT NOT NULL,
    MONTO_PAGADO             FLOAT NOT NULL DEFAULT 0,
    SALDO_PENDIENTE          FLOAT NOT NULL,
    FECHA_LIMITE_PAGO        VARCHAR(255) NOT NULL,
    ESTADO_CREDITO           VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_FACTURA)
        REFERENCES FACTURA(ID_FACTURA)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB;


-- 13 tabla Datos Producto
CREATE TABLE DATOSPRODUCTO (
    ID_SUCURSAL                  INT NOT NULL,
    ID_PRODUCTO                  INT NOT NULL,
    PRECIO_SUCURSAL_PRODUCTO     FLOAT NOT NULL,
    STOCK                        INT NOT NULL,
    ACTIVO_DATOSPRODUCTO         INT NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_SUCURSAL, ID_PRODUCTO),
    FOREIGN KEY (ID_SUCURSAL)    REFERENCES SUCURSAL(ID_SUCURSAL),
    FOREIGN KEY (ID_PRODUCTO)    REFERENCES PRODUCTO(ID_PRODUCTO)
);

-- 14 tabla Detalle Pedido
CREATE TABLE DETALLEPEDIDO (
    ID_DETALLE_PEDIDO  INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUCTO        INT NOT NULL,
    ID_PEDIDO          INT NOT NULL,
    CANTIDAD           INT NOT NULL,
    SUBTOTAL           FLOAT NOT NULL,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_PEDIDO)   REFERENCES PEDIDO(ID_PEDIDO)
);

-- 15 tabla Reparto Pedido
CREATE TABLE REPARTOPEDIDO (
    ID_PEDIDO               INT NOT NULL,
    ID_REPARTO_PEDIDO       INT NOT NULL,
    HORA_ASIGNACION         VARCHAR(255) NOT NULL,
    UBICACION_ENTREGA       VARCHAR(255) NOT NULL,
    FECHA_HORA_ENTREGA      VARCHAR(255),
    PRIMARY KEY (ID_PEDIDO, ID_REPARTO_PEDIDO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
);

-- 16 tabla Direccion
CREATE TABLE DIRECCION (
    ID_CLIENTE               INT NOT NULL,
    ID_DIRECCION             INT NOT NULL,
    ID_DEPARTAMENTO          INT NOT NULL,
    ID_MUNICIPIO             INT NOT NULL,
    ID_DISTRITO              INT NOT NULL,
    DIRECCION_ESPECIFICA     VARCHAR(255) NOT NULL,
    DESCRIPCION_DIRECCION    VARCHAR(255),
    ACTIVO_DIRECCION         INT NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_CLIENTE, ID_DIRECCION),
    FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
        REFERENCES DISTRITO(ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
);
